language: python
python:
  - "2.7"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
install: "pip install flake8"
script:
  - flake8
  - python setup.py sdist
